---
title: "Dashboard Introduction"
author: "Billy Houseman"
output: html_document
---
<style>
body {
text-align: justify;
font-size: 14pt;
}
</style>
---

# Summary of Findings
Exploring the dashboard we see that Canada has the highest number of users, 411. However, it appears that Canada has the lowest engagement with 69.4 average spins per user. Whereas China, with only 21% of the player base has the highest engagement, with 150 average spins per user. Exploring the dashboard at a high level (all countries) we can develop a profile of our average user. The most popular operating system is Android and the most popular browser is Mobile Safari 15.5. The most popular method of playing is landacape. The most popular method of spinning the slots is tapping and the most popular method of stopping the slot is 'normal'. 

The results of this dashboard provide some insights and value, such as, why is Canada's engagement so low and how can we increase this? Additionally, by creating a profile of our average user we can focus resources on improving the experiences for this user such as optimising the game when played in portrait mode and providing engaging feedback when users tap to spin.


# How to use this dashboard
Welcome to my dashboard for the Data Analyst test. To view the dashboard please click the 'Main Dashboard' tab on the left. Within this dashboard you can use the filter option at the top to filter the countries. 

Note: If more than one country is selected (i.e., Canada and China) the value boxes will display total values for the combined countries. If you would like to explore individual countries please change the filter to only that country. By selecting one country only, the plots will change to display a more detailed breakdown.


# The code
The code for the Shiny Web app and the code used to prepare the data can be found here: 

As a general overview of the steps taken, I first parsed the JSON column and extracted the columns of intrest. I then calculated all of the Key Performance Indicators (KPIs) and stored them in individual tables. I then pivoted these tables into a longer format and bound all the tables together by row. I chose to do this to account for scalability, as the number of countries increases and the rows of data increases, doing these calculations within the app would be slow.

Note: For some of the KPIs, i.e., Most popular browser, I produced a count for each users unique browser. However, some users used more than one browser. For this dashboard if a user used more than one browser, both counts will be included.

# Why I chose R
I chose to use R for this dashboard over other popular choices such as Excel and Tableau for a number of reasons. Firstly, as RShiny uses the R programming langauge, the dashboard and calculations are transparent and easily recreated and version controlled using GIT. Secondly, R and RShiny can easily be intergrated into existing data pipelines and allow for automation and scaling. Finally, RShiny allows for increased customisation using CSS and HTML